Feat/6373 example gold workload
Ensono/stacks-azure-data pull request #197
Opened 2023-09-26 11:17 UTC by james-horrocks

#### 📲 What

Add an example gold layer workload using the previous silver layer examples

#### 🤔 Why

So that the platform contains working examples of all stages of a medallion architecture data lake

#### 🛠 How

`gold_movies_example` added as a pyspark workload

#### 👀 Evidence

Documentation not yet updated

#### 🕵️ How to test

Unit tests can be run using `make test` or `poetry run python -m pytest de_workloads/processing/gold_movies_example/tests/unit`

need to check deployment in Azure...

#### ✅ Acceptance criteria Checklist

- [ ] Code peer reviewed?
- [ ] Documentation has been updated to reflect the changes?
- [ ] Passing all automated tests, including a successful deployment?
- [ ] Passing any exploratory testing?
- [x] Rebased/merged with latest changes from development and re-tested?
- [x] Meeting the Coding Standards?

2023-09-28 08:37 UTC, james-horrocks commented on de_templates/processing/processing_template/data_factory/pipelines/arm_template.json.jinja
I used datastacks to generate the gold example and this fix in the generated file was needed to deploy successfully

2023-09-29 16:15 UTC, adurkan-amido requested changes
Looks good - just a few suggestions.

2023-09-29 16:15 UTC, adurkan-amido commented on de_workloads/processing/gold_movies_example/spark_jobs/process.py
> +    output_filepath = get_adls_file_url(GOLD_CONTAINER, "movies")
We should use the `OUTPUT_PATH_PATTERN` above, and write the table to something like `movies/movie_ratings_agg`

2023-09-29 16:15 UTC, adurkan-amido commented on de_workloads/processing/gold_movies_example/spark_jobs/process.py
> +    output_df = join_metadata_and_ratings(metadata, avg_ratings)
As these 2 functions are one liners, I think we should just combine into one transformation function.
Also looking at the output table - it's all a bit contrived as they're only examples, but perhaps the drop the `belongs_to_collection` column, as wouldn't want something nested in the gold table.

2023-09-29 16:15 UTC, adurkan-amido commented on docs/workloads/azure/data/etl_pipelines/data_processing.md
> +In Data Factory a standard data processing pipeline is as simple as this example:
```suggestion
In Data Factory a data processing pipeline can be as simple as this example:
```

2023-09-29 16:15 UTC, adurkan-amido commented on de_workloads/processing/gold_movies_example/README.md
> +# Data Processing Template Workload
Might be good to update this readme with a brief overview of the workload (and we should do the same for the others).

2023-09-29 16:26 UTC, adurkan-amido commented on docs/workloads/azure/data/etl_pipelines/data_processing.md
As a reminder - these updates will also need applying in the main docs repo.

2023-10-02 09:02 UTC, james-horrocks commented on de_workloads/processing/gold_movies_example/spark_jobs/process.py
> +        )
We certainly could and I'm happy to do that.
My original thinking was that this saved repetitive code when loading from many tables, but I only ended up loading from 2 so it makes less sense now

2023-10-02 13:43 UTC, adurkan-amido approved these changes

2023-10-02 13:50 UTC, merged